### ISSUE TITLE
hiera5 support

### ISSUE THREAD

**Issue by rendhalver** [voxpupuli/hiera-eyaml-gpg#39]
Hi gang,

I am trying to get this to work with hiera5.
From what I can tell this isn't even working at all.

Can someone confirm whether this works with hiera5?

**Comment by invidian** [comment]
Year ago I found out that it's not even working with hiera 3, so I assume this project is dead.

**Comment by rendhalver** [comment]
We have been using it in hiera3 for quite a while and it still works.

**Comment by rwaffen** [comment]
it is working in hiera5 but slowing down my compile times by 3-10x ... i think there are some performance issues

**Comment by sihil** [comment]
Hi all. I'm regret that since I don't really use puppet/hiera in my day job anymore that this project doesn't get prioritised. I've approached voxpupuli to see if they would be interested in adopting it and hopefully making it work better with hiera 5. My understanding is that you might be able to get it to work to some extent using `hiera3_backend`.

**Comment by rendhalver** [comment]
I did manage to get it to work with hiera5 and then forgot I opened this issue.
I am not working with puppet as much these days either.

**Comment by riton** [comment]
@rendhalver do you by any chance, remember how you did make it work with Hiera v5 ?

**Comment by rendhalver** [comment]
I can't remember why it didn't initially.
It definitely works now.
This is what each environments config looks like for hiera 5 if that helps.

It may have been how we were specifying the options.
```
---
version: 5
defaults:
  datadir: data

hierarchy:
  - name: "Global data (encrypted)"
    lookup_key: eyaml_lookup_key
    paths:
      - "nodes/%{facts.networking.fqdn}.yaml"
      - "clientcert/%{trusted.clientcert}.yaml"
      - "hostname/%{facts.networking.hostname}.yaml"
      - "environment/%{facts.city}/%{facts.phrg_env}.yaml"
      - "environment/%{facts.phrg_env}.yaml"
      - "environment/%{facts.phrg_env}/%{facts.role}.yaml"
      - "environment/%{facts.phrg_env}/%{facts.role}/%{facts.subrole}.yaml"
      - "role/%{facts.role}/%{facts.subrole}.yaml"
      - "role/%{facts.role}.yaml"
      - "city/%{facts.city}.yaml"
      - "OS/%{facts.os.name}/%{facts.os.release.major}.yaml"
      - "common.yaml"
    options:
      encrypt_method: gpg
      gpg_gnupghome: "/etc/puppetlabs/gnupg"
      gpg_always_trust: true
gpg_recipients_file: "hiera-eyaml-gpg.recipients"
```
